### ISSUE TITLE
Task 5: Report

### ISSUE THREAD

**Issue by jmaab** [jmaab/CMPS-455-Project-2#6]
```[tasklist]
### Task 1
- [ ] Describe Design & Implementation
- [ ] Answer: Is there any chance of deadlock in this simulation? What changes could cause deadlocks?
permission?
### Task 2
- [ ] Describe Design & Implementation
- [ ] Answer -- How does this task compare with Task 1? Which is easier to implement?
- [ ] Answer -- What is the importance of protection in a multi-user system? What could happen if all users were granted equal permission?
### Task 3
- [ ] Describe Design & Implementation
- [ ] Answer: What disadvantages do capability lists introduce given a more domain-based approach?
### Task 4
- [ ] Describe Design & Implementation
### Task 5 (Report)
- [ ] Answer: What is the importance of protection in a multi-user system? What could happen if all users were granted equal 
```
